name: Generate Faith and Focus Playlist

on:
  schedule:
    - cron: "10 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate playlist recommendations
        uses: lowlighter/metrics@latest
        with:
          user: MahdiBuilds
          token: NOT_NEEDED
          filename: assets/metrics/faith-and-focus.svg
          base: ""
          plugin_music: yes
          plugin_music_provider: youtube
          plugin_music_mode: playlist
          plugin_music_playlist: https://music.youtube.com/playlist?list=PL4gvDAHWfnPZ-P5iL7-7YLCDOYKHBjEKK
          plugin_music_limit: 4
