name: Generate Website Performance Reports

on:
  workflow_dispatch:
  schedule:
    - cron: "20 3 * * 1"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Audit MahdiBlogs
        uses: lowlighter/metrics@latest
        with:
          user: MahdiBuilds
          token: NOT_NEEDED
          filename: assets/metrics/pagespeed-mahdiblogs.svg
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://mahdiblogs.com

      - name: Audit Feather Universe
        uses: lowlighter/metrics@latest
        with:
          user: MahdiBuilds
          token: NOT_NEEDED
          filename: assets/metrics/pagespeed-feather.svg
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://featheruniverse.com
